### ISSUE TITLE
Wrong values of the eccentricity distribution -u parameter

### ISSUE THREAD

**Issue by ruggero-valli** [amusecode/SeBa#14]
The documentation says:
> -U/u eccentricity option: 
> 	.0) Equal eccentricity
> 	.1) Power Law
> 	.2) Thermal distribution [default] Option -U requires one of the following strings:
> 	(Equal_ecc, ecc_Power_Law, Thermal_Distribution) -u requires appropriate interger (see double_star.h)

But what really happens when setting the value of u is:
> .0) Unknown_eccf
> .1) Equal_ecc
> .2) ecc_Power_Law
> .3) Thermal_Distribution

I believe it could be fixed by setting Unknown_eccf=-1 at line 190 of starbase.h

**Comment by silviatoonen** [comment]
Solved. Thanks for reporting!
