### ISSUE TITLE
eccentricity power law distribution produces nan

### ISSUE THREAD

**Issue by ruggero-valli** [amusecode/SeBa#15]
When running the code with the option -U Power_Law, the output file SeBa.data contains -nan in place of the separation and the eccentricity (columns 5 and 6).
It could be caused by a bug at line 560 of initdouble.c
I believe it could be fixed by changing
`ecc = get_random_eccentricity(e_min, e_max, ef, m_prim+m_sec);`
to
`ecc = get_random_eccentricity(e_min, e_max, ef, e_exp);`

**Comment by silviatoonen** [comment]
Solved. Thanks for reporting!
