### ISSUE TITLE
Wrong string values for the parameter -U

### ISSUE THREAD

**Issue by ruggero-valli** [amusecode/SeBa#16]
The documentation says that the parameter -U needs one of the following strings to be passed:

> Equal_ecc, ecc_Power_Law, Thermal_Distribution

Actually, the code only accepts one of the following strings:

> Equal_ecc, Unknown_eccf, Power_Law

Therefore, to set a power law distribution, one needs to write `-U Power_Law`, not `-U ecc_Power_Law`, as indicated in the documentation. Furthermore, it is currently impossible to set a thermal distribution using the -U parameter.

Reference: `extract_eccentricity_distribution_type_string` function in initdouble.C

**Comment by silviatoonen** [comment]
Solved

**Comment by silviatoonen** [comment]
Thanks for reporting!
