### ISSUE TITLE
Wrong parameter in mass ratio distribution

### ISSUE THREAD

**Issue by ruggero-valli** [amusecode/SeBa#17]
In file `initdouble.c`, lines 165-186:

    char* type_string(mass_ratio_distribution qf) {
    
        local char  qf_name[SEED_STRING_LENGTH];
        switch(qf) {
           case Equal_q:
                sprintf(qf_name, "Equal_q"); 
	        break;	    
           case Flat_q:
                sprintf(qf_name, "Flat_q"); 
	        break;	    
           case qf_Power_Law:
                sprintf(qf_name, "Power_Law"); 
	        break;	    
           case Thermal_Distribution:
                sprintf(qf_name, "Hogeveen"); 
	        break;	    
           default:
                sprintf(qf_name, "Unknown_qf"); 
	        break;
        }
        return qf_name;
    }

I believe that line 178 should be `case Hogeveen` instead of `case Thermal_Distribution`, because Thermal distribution is a type of eccentricity distribution, not mass ratio.

As of now, this does not create problems, because Thermal_Distribution and Hogeveen are both equal to 3. But if the issue [ Wrong values of the eccentricity distribution -u parameter #14 ](https://github.com/amusecode/SeBa/issues/14) is resolved in the way I suggested, then Thermal_Distribution would become 2, and this would break the code.

**Comment by silviatoonen** [comment]
Solved

**Comment by silviatoonen** [comment]
Thanks for reporting!
